using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo{Title = "GeminiPostSQL REST API", Version = "v1", Description = "REST API with AI-Assisted Endpoints" });

    c.EnableAnnotations();
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "GeminiPostSQL REST API V1");
        options.DefaultModelsExpandDepth(-1);
        options.DocumentTitle = "GeminiPostSQL API";
        options.EnableFilter();
        options.DisplayRequestDuration();
        options.HeadContent = "<link rel=\"icon\" type=\"image/png\" href=\"/Img/favicon.png\">"
                            + "<span class=\"header\">&emsp;Developed by Komma, powered by Google's Gemini AI and Swagger UI generated by Swashbuckle</span>";
        options.InjectStylesheet("/Style/style.css");
    });
}

app.UseStaticFiles();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
